default: &default
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://localhost") %>
  pool: <%= ENV.fetch("DB_MAX_POOL", 7) %>
  username: postgres
  password:

development:
  <<: *default
  database: burn_development

test:
  <<: *default
  database: burn_test

production:
  <<: *default
  pool: <%= ENV.fetch("DB_MAX_POOL", 10) %>
